### PR TITLE
Adds Keithley OSS badge to README

### PR DESCRIPTION
**Pull request by nlynchjo**
### Pull Request Checklist

Please review the [Contribution Guidelines](../README.md#contributing) before submitting.

- [ ] Pulling against the `dev` branch (left side).
- [x] You have previously submitted a Contributor License Agreement or have contacted a maintainer to request one.

### Type (Select only one)

- [ ] Bug fix
- [ ] Working example
- [ ] In-progress example (need Keithley help)
- [ ] In-progress example (do not need Keithley help)

### Description

Describe your pull request here.

### CODE REVIEW

**Comment by nlynchjo** [comment]
okay to merge since this is just a readme update?

**Comment by nlynchjo** [comment]
Any update on latest PRs? Anything we can help with?

**Comment by jbrown1234** [comment]
Nothing yet – still pushing at the end of two project efforts.

Josh Brown
Factory Applications Engineer
E/ josh.brown@keithley.com<mailto:josh.brown@keithley.com>
T/ +1 440.498.2960 x 2960M/ +1 440.213.7956
tek.com<http://tek.com/>

[Twitter]<https://twitter.com/tektronix>[Facebook]<https://www.facebook.com/tektronix>[LinkedIn]<https://www.linkedin.com/company/tektronix>[Google+]<https://plus.google.com/+tektronix>[Instagram]<http://www.instagram.com/tektronixofficial/>[YouTube]<https://www.youtube.com/user/tektronix>

[KEILOGO_BLOOP_10pct]

[<span class="fill" attr="company"></span>]<http://tek.com/>

Please be advised that this email may contain confidential information. If you are not the intended recipient, please notify us by email by replying to the sender and delete this message. The sender disclaims that the content of this email constitutes an offer to enter into, or the acceptance of, any agreement; provided that the foregoing does not invalidate the binding effect of any digital or other electronic reproduction of a manual signature that is included in any attachment.

**Comment by zkoppert** [comment]
@nlynchjo Okay to merge now?

**Pull request merged**
